version: "3.8"
services:
  ome:
    image: ovenmediaengine/ovenmediaengine:latest
    ports:
      - "1935:1935"
      - "80:80"
      - "8888:8888"
      - "4443:4443"
    volumes:
      - ./Server.xml:/etc/ome/Server.xml
      - ome_hls:/var/ome/hls

volumes:
  ome_hls:
